### PR TITLE
Refacor

### PR DESCRIPTION
**Pull request by petrzpav**
1. boolean function names and usage
1. remove unnecessary `else: return` after loops
1. unify code style

### CODE REVIEW

**Review by martapavelka — DISMISSED** [review]
Děkuji!

**Review by martapavelka — COMMENTED** [review]
Without changing anything, Collab gives error in the 1st cell, line 66: ValueError: max() arg is an empty sequence

**Comment by petrzpav** [comment]
There was an error in loading input matrix from `stdin`, see [fix](https://github.com/martapavelka/scpc/pull/3/commits/a9cd04f692a1927f6e82c712a7130a8ba6782c46) on line 146 and 147. Now it can handle empty input form Colab.

**Review by martapavelka — APPROVED** [review]
I tested it for several complexes and it looks good to me!

**Pull request merged**
